### ISSUE TITLE
Templates lack an example for plugins which require configuration via Sensu settings

### ISSUE THREAD

**Issue by cwjohnston** [GhostLyrics/sensu-plugin-doc-draft#3]
Some plugins, handlers in particular, require configuration defined in Sensu settings. For example the [sensu-plugins-hipchat handler](https://github.com/sensu-plugins/sensu-plugins-hipchat) requires configuration for sending alerts to a HipChat API endpoint.

I think plugins which require configuration via Sensu settings should be documented in the readme, and it would be great if such documentation also linked to the [Sensu Configuration Reference doc](https://sensuapp.org/docs/latest/reference/configuration.html) or similar.

**Comment by GhostLyrics** [comment]
I'll whip up a suggestion, probably an optional 'configuration' section after 'installation' with some sample text and a sample JSON.
